name: "flask test template"
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
      - name: "Deploy to EC2"
        run: "cd flask-app/\n  git pull origin master\n  source venv/bin/activate\n  # Additional setup and deployment commands (e.g., database migrations)\n  supervisorctl restart your_flask_app\nEOF\n"
        env:
          HOSTNAME: "${{secrets.HOST_DNS}}"
          USER_NAME: "${{secrets.USERNAME}}"
          PRIVATE_KEY: "${{secrets.EC2_SSH_KEY}}"
